config/routes.rb
Reddit::Application.routes.draw do
  resources :subs do
    resources :links
  end

  root to: "subs#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :creator_id, :sub_id
  validates :title, :url, :creator_id, :sub_id, :presence => true

  belongs_to :sub
  belongs_to(
    :creator,
    :class_name => "User",
    :foreign_key => :creator_id,
    :primary_key => :id
  )
end

app/models/sub.rb
class Sub < ActiveRecord::Base
   attr_accessible :moderator_id, :name, :creator_id

   has_many :links

   belongs_to(
   :moderator,
   class_name: "User",
   foreign_key: :moderator_id,
   primary_key: :id)


end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password
  validates :username, :password, :presence => true
  validates :password, :length => { :minimum => 6 }
  validates :username, :uniqueness => true

  has_many(
  :links,
  class_name: "Link",
  foreign_key: :creator_id,
  primary_key: :id
  )


  has_many(
    :moderated_subs,
    :class_name => "Sub",
    :foreign_key => :moderator_id,
    :primary_key => :id
  )

  def password=(password)
    @password = password
    self.password_hash = BCrypt::Password.create(password)
  end

  def password_is?(password)
    BCrypt::Password.new(self.password_hash).is_password?(password)
  end

  def reset_token
    self.token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.token
  end


  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user && user.password_is?(password)
      user
    else
      nil
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show
    @link = Link.find(params[:id])
  end

  def create
    @link = Sub.find(params[:sub_id]).links.new(params[:link])
    save_model!(@link, sub_links_url(params[:sub_id])
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(params[:sub])

    save_model!(@sub)
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def save_model!(model, redirect_url = nil)

    if model.save # change to snake case
      redirect_to  redirect_url || model #send("#{model.class.to_s.downcase}_url", model )
    else
      flash[:errors] = model.errors.full_messages
      render :new
    end
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/layouts/_authenticity.html.erb
<input type="hidden" name="form_authenticity_form" value="<%= form_authenticity_token %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/show.html.erb
<h1>Title</h1>
  <%= @link.title %>

<h2>URL</h2>
<%= @link.url %>

app/views/subs/index.html.erb
<h1>Reddit</h1>
<% @subs.each do |sub| %>
  <h1><%= sub.name %><h1>
  <% sub.links.each do |link| %>
    <p><%= link_to link.title, sub_link_url(sub,link) %></p>
    <% end%>
<% end %>

<%= link_to "New Sub", new_sub_url %>

app/views/subs/new.html.erb
Create Subreddit
<form action="<%= subs_url %>" method="post">
  <label>Name
  <input type="text" name="sub[name]">
  </label>

  <label>Creator ID
  <input type="text" name="sub[moderator_id]">
  </label>

  <%= render :partial => "layouts/authenticity" %>
  <input type="submit" value="Click">
</form>

app/views/subs/show.html.erb
<% @sub.links.each do |link| %>
  <p><%= link.title %></p>
  <p><%= link.url %></p>
<% end %>

<h1>New Link</h1>
<form action="<%= sub_links_url(@sub) %>" method="post">

  <label>Link Title
  <input type="text" name="link[title]">
  </label>

  <label>URL
  <input type="text" name="link[url]">
  </label>

  <%= render partial: "layouts/authenticity" %>
  <input type="submit" value="Click">
</form>